spring:
  application:
    name: notification-service
  datasource:
    url: ${PG_DB_URL}/notification_service_db
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8087

