spring:
  datasource:
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: kasunyahimani@gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost