spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/auth/**, /api/users/**, /api/instructors/**, /api/instructor-applications/**
            - id: course-service
              uri: http://course-service:8082
              predicates:
                - Path=/api/courses/**, /api/lessons/**, /api/enrollments/**
            - id: assessment-service
              uri: http://assessment-service:8083
              predicates:
                - Path=/api/assessments/**
            - id: media-service
              uri: http://media-service:8086
              predicates:
                - Path=/api/files/**
            - id: notification-service
              uri: http://notification-service:8087
              predicates:
                - Path=/api/notifications/**
            - id: payment-service
              uri: http://payment-service:8085
              predicates:
                - Path=/api/payments/**, /api/subscriptions/**, /api/subscription-plans/**, /api/webhooks/**

# CORS Configuration for Production - Frontend domains that call the API
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:https://app.levelups.app,https://admin.levelups.app}"

# Eureka disabled for Kubernetes deployment
eureka:
  client:
    enabled: false