spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/levelup_course_db
      database: levelup_course_db
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost