spring:
  application:
    name: course-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 2
#      idle-timeout: 30000     # 30s
#      max-lifetime: 600000    # 10 min
#      connection-timeout: 20000  # 20s wait before failing
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

#eureka:
#  client:
#    service-url:
#      defaultZone: http://152.42.189.244:8761/eureka/
#  instance:
#    prefer-ip-address: true
