apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: levelup-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: heshanheshan/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ALLOWED_ORIGINS
        resources:
          requests:
            memory: "384Mi"    # Gateway needs moderate memory for routing
            cpu: "200m"        # Reduced CPU for routing logic
          limits:
            memory: "512Mi"    # Lower limit, sufficient for gateway
            cpu: "400m"
        # Health checks - OPTIMIZED FOR GKE
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: levelup-learning
  annotations:
    # Apply the backend config for CORS and health checks
    cloud.google.com/backend-config: '{"default": "api-backend-config"}'
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP