apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assessment-service
  template:
    metadata:
      labels:
        app: assessment-service
    spec:
      containers:
      - name: assessment-service
        image: assessment-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: PG_DB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DB_URL
        - name: PG_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DB_USERNAME
        - name: PG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_DB_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: default
spec:
  selector:
    app: assessment-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP