apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backend-config
  namespace: levelup-learning
spec:
  timeoutSec: 40

  # CORS is handled by Spring Boot API Gateway
  # GKE BackendConfig doesn't support CORS field, so we rely on application-level CORS

  # Health check - OPTIMIZED FOR GKE LOAD BALANCER
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /health
    port: 8080

  connectionDraining:
    drainingTimeoutSec: 60

  logging:
    enable: true
    sampleRate: 1.0

  sessionAffinity:
    affinityType: "CLIENT_IP"
