apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backend-config
  namespace: levelup-learning
spec:
  timeoutSec: 40

  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /actuator/health
    port: 8080

  connectionDraining:
    drainingTimeoutSec: 60

  logging:
    enable: true
    sampleRate: 1.0

  sessionAffinity:
    affinityType: "CLIENT_IP"
