apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: levelup-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
      - name: media-service
        image: heshanheshan/media-service:latest
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: PG_DB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DB_URL
        - name: PG_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DB_USERNAME
        - name: PG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_DB_PASSWORD
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SECRET_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_REGION
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_S3_BUCKET_NAME
        resources:
          requests:
            memory: "256Mi"    # File upload/download operations
            cpu: "100m"        # I/O intensive, less CPU needed
          limits:
            memory: "512Mi"    # Higher limit for file processing
            cpu: "200m"
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8086
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8086
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: levelup-learning
spec:
  selector:
    app: media-service
  ports:
  - port: 8086
    targetPort: 8086
  type: ClusterIP