apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: levelup-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: heshanheshan/notification-service:latest
        ports:
        - containerPort: 8087
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: PG_DB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DB_URL
        - name: PG_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PG_DB_USERNAME
        - name: PG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_DB_PASSWORD
        - name: RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PASSWORD
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SENDGRID_API_KEY
        - name: FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FROM_EMAIL
        resources:
          requests:
            memory: "256Mi"    # Lightweight notification processing
            cpu: "100m"        # Low CPU for email sending
          limits:
            memory: "384Mi"    # Sufficient for notification queues
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: levelup-learning
spec:
  selector:
    app: notification-service
  ports:
  - port: 8087
    targetPort: 8087
  type: ClusterIP