apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: course-service-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: course-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: media-service-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: media-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: assessment-service-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: assessment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-pdb
  namespace: levelup-learning
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: rabbitmq