apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  # External Database Passwords (base64 encoded)
  # Replace with your actual DigitalOcean PostgreSQL password
  PG_DB_PASSWORD: RzdrUDR0WjltUjJ3UTh4TA==
  
  # External MongoDB password (included in connection string)
  # If using MongoDB Atlas, the password is in the connection string
  
  # RabbitMQ Password (base64 encoded)
  # Original: password
  RABBITMQ_PASSWORD: cGFzc3dvcmQ=
  
  # Google OAuth Configuration (base64 encoded)
  # Replace with actual values - these are placeholders
  GOOGLE_CLIENT_ID: ODcxMDU3NTAyMzc2LWMwM2t2ZGx2MmQ5aTBoOW52aWZ0dXJub2dhaGE0ZzgyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLU1SbUFrSG9lVm1ramNvMEdlSldHRXJQb2U2Y0Y=
  
  # AWS Credentials (base64 encoded)
  # Replace with actual values - these are placeholders
  AWS_ACCESS_KEY: ZQUtJQVdRT09UMlNTWlU3SkQyM0Q=
  AWS_SECRET_KEY: TDBzSmMyUTU5cm1ZUDVsNEVkOGUrZXVvbVdpZitqZ2RiNERUd3BXNw==
  
  # Stripe Configuration (base64 encoded)
  # Replace with actual values - these are placeholders
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVMzY3RNRkdvemJYRzlCU1pFOHhiRDdLUFZwN3lYOFZuTlJhVTNPMHA2QUgyeko3VTJBOFFTUFNHRlNna1J3Z012Z1NpMVVJWnBPcjRHV0RQWDdaSkN4eDAwR2ZHdDQ5Q1E=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfcjBQOWRPSjRzNnFndlQ3TjJyTlNyVTREOUtRSDVpWmk=
  
  # SendGrid Configuration (base64 encoded)
  # Replace with actual values - these are placeholders
  SENDGRID_API_KEY: U0cueEd3aTBjNHhUcmVvSlh2Y3luZm1yQS42bVpxd1htajhSMENHZC1aMktSNm9HUlRPcUVJeXlyNDhyMF80QjAwd0RZ
  
  # Certifier API Key (base64 encoded)
  # Replace with actual values - these are placeholders
  CERTIFIER_API_KEY: Y2ZwX1VyalBuYnFNaTF5WlM3WW5GcGNJS0kwV2c5Z0JqdndYbHpibg==
  
  # JWT Secret (base64 encoded)
  # Original: Zx9f2@qL1!mYkBv7$P0tWnRzX4eU8gJhCq3LsDa6#FtVbMpN
  JWT_SECRET: WnhxZjJAcUwxIW1Za0J2NyRQMHRXblJ6WDRlVThnSmhDcTNMc0RhNiNGdFZiTXBOCg==