spring:
  application:
    name: payment-service
  datasource:
    url: ${PG_DB_URL}/payment_service_db
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

webclient:
  connection-timeout: 5000
  read-timeout: 10000