spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

webclient:
  connection-timeout: 5000
  read-timeout: 10000