spring:
  datasource:
    # External DigitalOcean PostgreSQL
    url: ${PG_DB_URL}/assessment_service_db
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000

# Eureka disabled for Kubernetes deployment
eureka:
  client:
    enabled: false