spring:
  application:
    name: assessment-service
  datasource:
    url: ${PG_DB_URL}/assessment_service_db
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost