spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: ${MEDIA_DB_URL}
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 8086

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

#eureka:
#  client:
#    service-url:
#      defaultZone: http://152.42.189.244:8761/eureka/
#  instance:
#    prefer-ip-address: true
