spring:
  application:
    name: media-service
  datasource:
    url: ${PG_DB_URL}/media_service_db
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 8086
