spring:
  datasource:
    # External PostgreSQL database
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}




cloud:
  aws:
    credentials:
      access-key: dummy-access-key
      secret-key: dummy-secret-key
    region:
      static: us-east-1
    s3:
      bucket-name: dummy-bucket

# Eureka disabled for Kubernetes deployment
eureka:
  client:
    enabled: false