spring:
  datasource:
    # External DigitalOcean PostgreSQL
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: user
    password: password

jwt:
  secret: Zx9f2@qL1!mYkBv7$P0tWnRzX4eU8gJhCq3LsDa6#FtVbMpN
  jwtExpirationMs: 3600000 # 1 hour

google:
  clientId: dummy-client-id

# Eureka disabled for Kubernetes deployment
eureka:
  client:
    enabled: false