spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/levelup_auth_db
      database: levelup_auth_db
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"
      resourceserver:
        jwt:
          secret: Zx9f2@qL1!mYkBv7$P0tWnRzX4eU8gJhCq3LsDa6#FtVbMpN
          jwtExpirationMs: 3600000 # 1 hour

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
