spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/levelup_user
      database: levelup_user

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost