name: Java CI with Maven

on:
  pull_request:
    branches: [ "main","deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [user-service, notification-service, assessment-service, media-service]

    env:     
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      PG_DB_URL: ${{ secrets.PG_DB_URL }}
      PG_DB_USERNAME: ${{ secrets.PG_DB_USERNAME }}
      PG_DB_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build & Test Service
      working-directory: ${{ matrix.service }}
      run: |
        run: mvn clean verify -Dspring.profiles.active=local
