name: Build and Deploy Payment Service

on:
  push:
    branches: [ deploy ]     # Build + deploy on this branch
    paths:
      - 'payment-service/**'

env:
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: asia-south1
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: payment-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Setup Java
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # # 3️⃣ Run tests
    # - name: Run tests
    #   working-directory: ${{ env.SERVICE_NAME }}
    #   run: mvn clean test

    # 4️⃣ Build application
    - name: Build application
      working-directory: ${{ env.SERVICE_NAME }}
      run: mvn clean package -DskipTests

    # 5️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6️⃣ Build Docker image (two tags: commit SHA + latest)
    - name: Build Docker image
      working-directory: ${{ env.SERVICE_NAME }}
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
                     -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest .

    # 7️⃣ Push Docker images
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest

    # 8️⃣ Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 9️⃣ Setup Google Cloud CLI
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 🔟 Install GKE Auth Plugin (required for Autopilot)
    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin -q

    # 1️⃣1️⃣ Deploy to GKE (only on deploy push)
    - name: Deploy to GKE
      if: github.ref == 'refs/heads/deploy'
      run: |
        # Get cluster credentials
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

        # Update deployment image
        kubectl set image deployment/$SERVICE_NAME \
          $SERVICE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:${{ github.sha }} \
          --namespace=levelup-learning

        # Wait for rollout to complete
        kubectl rollout status deployment/$SERVICE_NAME --namespace=levelup-learning