name: Java CI with Maven

on:
  pull_request:
    branches: [ "main","deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [course-service, payment-service, media-service, notification-service, user-service, payment-service]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build & Test Service
      working-directory: ${{ matrix.service }}
      run: mvn test -Dspring.profiles.active=test
